name: Mockaccino CI/CD
run-name: Mockaccino - ${{ github.ref_name }}
on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
  pull_request_target:
    types:
      - opened
      - edited
    branches:
      - 'main'
jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      dist_directory: ${{ github.workspace }}\dist
      solution_name: Mockaccino.sln
      test_project_path: tests\Mockaccino.UnitTests\Mockaccino.UnitTests.csproj
      pack_project_path: src\Mockaccino\Mockaccino.csproj
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.401

      - name: Execute Tests
        run: dotnet test $env:test_project_path --configuration Release --runtime win-x86
